(eval-when-compile
  (require 'color-theme))

(defun color-theme-hipplej ()
  "Color theme by hipplej. Created 2007-05-19."
  (interactive)
  (color-theme-install
   '(color-theme-hipplej
	 ((background-color . "black")
	  (background-mode . dark)
	  (border-color . "black")
	  (cursor-color . "green")
	  (foreground-color . "white")
	  (mouse-color . "sienna1"))
     (region ((t (:foreground "white" :background "blue"))))
     (default ((t (:background "black" :foreground "white"))))
	 (cperl-array-face ((t (:foreground "orangered" :bold t))))
	 (cperl-hash-face ((t (:foreground "Red" :bold t))))
	 (cperl-nonoverridable-face ((t (:foreground "orange" :bold t))))
	 (custom-button-face ((t (:bold t :foreground "#3fdfcf"))))
	 (custom-group-tag-face ((t (:underline t :foreground "blue"))))
	 (custom-saved-face ((t (:underline t :foreground "orange"))))
	 (custom-state-face ((t (:foreground "green3"))))
	 (custom-variable-button-face ((t (:bold t :underline t :foreground "white"))))
	 (dired-face-permissions ((t (:foreground "green3"))))
	 (font-latex-bold-face ((((class color) (background light)) (:bold t))))
	 (font-latex-italic-face ((((class color) (background light)) (:italic t))))
	 (font-latex-math-face ((((class color) (background light)) (:foreground "green3"))))
	 (font-latex-sedate-face ((((class color) (background light)) (:foreground "gold"))))
	 (font-lock-comment-face ((t (:foreground "#ee7600"))))
	 (font-lock-doc-string-face ((t (:foreground "green3"))))
	 (font-lock-function-name-face ((t (:foreground "#3366FF" :bold t))))
	 (font-lock-keyword-face ((t (:foreground "#f939ff"))))
	 (font-lock-preprocessor-face ((t (:foreground "red"))))
	 (font-lock-reference-face ((t (:foreground "green3"))))
	 (font-lock-string-face ((t (:foreground "green3"))))
	 (font-lock-type-face ((t (:foreground "#886fff" :bold t))))
	 (font-lock-variable-name-face ((t (:foreground "#9a2fff" :bold t))))
	 (font-lock-warning-face ((t (:foreground "Violetred" :bold t))))
	 (highlight ((t (:foreground "red3" :background "white"))) t)
	 (isearch ((t (:foreground "red" :background "white"))) t)
	 (list-mode-item-selected ((t (:foreground "green3"))) t)
	 (message-cited-text ((t (:bold t))))
	 (secondary-selection ((t (:foreground "white" :background "red"))) t)
	 (text-cursor ((t (:foreground "black" :background "green3"))) t)
	 (zmacs-region ((t (:background "RoyalBlue"))) t))))

(provide 'color-theme-hipplej)
